on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get the version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Update version from tag
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: |
          echo "Version is: ${VERSION}"
          test -n "${VERSION}"
          echo "__version__ = \"${VERSION}\"" > pythonhere/version_here.py

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            "herethere/pythonhere:latest"
            "herethere/pythonhere:${{ steps.version.outputs.VERSION }}"

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
