#:kivy 1.0

#:import SettingPassword ui_here.settings_here.SettingPassword
#:import App kivy.app.App

<ScreenActionButton@ActionToggleButton>:
    group: "screen"
    screen: ""
    allow_no_selection: False
    on_release: App.get_running_app().root.switch_screen(self.screen)


<SettingPassword>:
    PasswordLabel:
        pos: root.pos
        font_size: "15sp"
        text: '*' * len(root.value or '')
